### ISSUE TITLE
Make the blacklist for configuration values configurable (ini, cvalue)

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#106]
`List<String> valueBlacklist = [ConfigurationConstants.CVALUE_PLACEHOLDER_RODDY_JOBID_RAW, 'PWD', Constants.PID_CAP, Constants.PID`

**Comment by vinjana** [comment]
RoddyCore/src/de/dkfz/roddy/config/validation/ScriptValidator.groovy
RoddyCore/src/de/dkfz/roddy/config/converters/BashConverter.groovy

**Comment by dankwart-de** [comment]
Solved / Ignored. We removed most of the blacklisted values, as we changed Roddys configuration value sort algorithm.
