### ISSUE TITLE
Malformed plugin version string may lead to silent loading wrong plugin version

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#108]
When "IndelPlugin-1.0.176-5-1" is used as directory name for the plugin and "IndelPlugin-1.0.175-4" is present, the older plugin version is used and *no error message or warning is issued*.

Desired behaviour?

Fail fataly: Idea is to "keep your plugin directories clean, or you are on your own"

I think warnings are not sufficient here. A meaningful error message needs to be shown.

**Comment by vinjana** [comment]
Related to issue #58. Find a solution that is safe (better safe than sorry).

**Comment by dankwart-de** [comment]
If we stick to this: Fail fataly (which I like), this will be a huge "problem" for some developers as they often make some sort of backups in their directory.

I think the clean directory mode could also apply for configuration directories.

**Comment by dankwart-de** [comment]
Just another comment. The behaviour IS right! The name  "IndelPlugin-1.0.176-5-1" is malformed and will not be considered as a plugin by Roddy. We have messages for that but there can be a lot of them. Also, the used plugin version is printed on startup! I know, that a lot of people tend to ignore the messages but then we really need to discuss how we handle it. Enforcing clean plugin directories is one way, with the mentioned problems. Just printing all ignored  directories is not a good way, the output can be too big.

**Comment by dankwart-de** [comment]
#58 has nothing to do with this issue and can actually be closed.

**Comment by vinjana** [comment]
Do you think, there are many people with tons of illegal plugin directory names who would be drowned by warning messages?

What I would not do is, introducing another "mode" argument. We need to find one way to do it and tell the users this is the way. So I still see these three options:
* leave it like it is (no message [I just checked])
* fail on malformed directory name
* issue warning about malformed directory name
