### ISSUE TITLE
LSF and PBS should write all output into one file

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#121]
See https://github.com/eilslabs/BatchEuphoria/issues/46 for how this is in LSF.

**Comment by dankwart-de** [comment]
Is this really a Roddy item? Or more like a BE item?

**Comment by vinjana** [comment]
In BE the thing is now implemented in such a way, that the stdout and stderr log have to be set to the same file such that all output is written to the same file. From an independent BE perspective, this is the best semantics. 

Therefore, in Roddy we need to do it like this. So the task is to ensure this being done.
