### ISSUE TITLE
Initial logging output of wrapper is missing

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#129]
All the logging output that should be produced with `set -x`, up to the line `RODDY_SCRATCH is set to ...` is missing from the STDERR log files.

**Comment by vinjana** [comment]
The problem was cause by incorrect redirections using the single `>` operator to `/dev/stderr`. Apparently, this reopens the output stream and only the last /dev/stderr file handle is returned to PBS/LSF to be returned as standard error.

In the future, use
* Use append operator `>> /dev/stderr`
* Globally redirect stdout and stderr to  stderr with `exec 1>&2`
* Locally redirect all output to stderr with `>&2 $command`

**Comment by dankwart-de** [comment]
You solved this right?

**Comment by vinjana** [comment]
Solved.
