### ISSUE TITLE
Implement configuration possibilities for the scratch directory

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#142]
#namely:
- Query from the job manager, if this is possible at all
- Get from ini
- Get from sideloaded xml
- Get from command line value or xml
- Fail Roddy instantly, if the variable is not set

**Comment by vinjana** [comment]
What is a sideloaded XML?

**Comment by dankwart-de** [comment]
Bad description. Sideloaded xmls are the xml files which are loaded additionally via a cli switch.

It is done now right? #145

**Comment by dankwart-de** [comment]
Resolved
