### ISSUE TITLE
Check licenses!

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#153]
See if we cover everything. There were quite some changes, don't want to miss things :D.

**Comment by vinjana** [comment]
Is this actually necessary? When we switch to Gradle (probably soon after the 2.4 switch) all dependencies will be downloaded via automatically none will be bundled.

**Comment by dankwart-de** [comment]
At least we need to check if the used libraries are compatible with ours.


Am 22. November 2017 5:06:40 nachm. schrieb Philip Reiner Kensche 
<notifications@github.com>:

**Comment by vinjana** [comment]
I will probably add the following to the Gradle file:
```gradle
    compile 'com.jcraft:jsch.agentproxy.jsch:0.0.9'               // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.pageant:0.0.9'            // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.sshj:0.0.9'               // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.usocket-nc:0.0.9'         // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.usocket-jna:0.0.9'        // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.connector-factory:0.0.9'  // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
    compile 'com.jcraft:jsch.agentproxy.sshagent:0.0.9'           // BSD-style, http://www.jcraft.com/jsch-agent-proxy/LICENSE.txt
```

Every compile or testCompile line in the gradle file has a license information added as comment. Please see the gradle branch.

**Comment by dankwart-de** [comment]
Ok, that should do it then. I'll close this issue then
