### ISSUE TITLE
Missing imported configurations are reported, but Roddy continues

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#154]
When configurations cannot be loaded, e.g. because the configuration directory containing them is missing, this is reported but Roddy continues. This does result in uninitialized configuration values and crashes. Could also be that this will result in wrong configurations (e.g. if later imports override values in earlier).

Should we not let Roddy die?

Here are the responsible sites in the code:

- `de/dkfz/roddy/config/loader/ConfigurationFactory.groovy:318`: throws
- `de/dkfz/roddy/config/loader/ConfigurationFactory.groovy:342`: swallows the exception and only writes a logger message

To accumulate errors I suggest we move the error accumulation from the ExecutionContext to the Roddy class. Any comments @dankwart-de ?

**Comment by dankwart-de** [comment]
Yes, we also discussed it. Better safe than sorry.


Am 22. November 2017 5:13:16 nachm. schrieb Philip Reiner Kensche 
<notifications@github.com>:
