### ISSUE TITLE
Plain scripts (.sh) files in workdir result in XML error

### ISSUE THREAD

**Issue by vinjana** [eilslabs/Roddy#197]
[Fatal Error] :11:39: Element type "cvalue" must be followed by either attribute specifications, ">" or "/>".
File /home/reisinge/tmp/get_snps.sh cannot be loaded! Error in config file! org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 39; Element type "cvalue" must be followed by either attribute specifications, ">" or "/>".

Here Roddy was executed from /tmp. This is a nuissances in will certainly hit all users, unless fixed soon.

Solutions:
* Require dedicated suffix other than `.sh` for shell-based workflows
* Mark shell-based workflow `.sh` files with special header
* Ignore all `.sh` files in workdir

**Comment by vinjana** [comment]
Not sure how to best solve this. Any comments @dankwart-de ?

**Comment by dankwart-de** [comment]
Well actually they have some sort of special header, which we can extend by a bit, but I wanted to keep them simple:

```
* The easy Bash config format.
     *
     * This is a very generic helper script which just converts a bash cfg to xml.
     * Not everything is covered, it's not built in yet and it needs a lot of improvement.
     * But for now, it works.
     * To run it faster from within IDEA, copy the content to a groovy console and start it.
     *
     * Basically a file which contains some info in the header and only config values.
     *
     * Example:
     * #name aConfig
     * #imports anotherConfig
     * #description aConfig
     * #usedresourcessize m
     * #analysis A,aAnalysis,TestPlugin:current
     * #analysis B,bAnalysis,TestPlugin:current
     * #analysis C,aAnalysis,TestPlugin:current
     *
     * outputBaseDirectory=/data/michael/temp/roddyLocalTest/testproject/rpp
     * preventJobExecution=false
     * UNZIPTOOL=gunzip
     * ZIPTOOL_OPTIONS="-c"
```

Actually I don't see the issue with pwd? It is so, that Roddy changes its working directory when it starts. 
I need to check, but I think that the header is not checked properly, when sh's are loaded.

**Comment by dankwart-de** [comment]
See #201 
"Invalid" .sh files should now be ignored (with a rare message stating that this is not a valid Roddy file)
