### ISSUE TITLE
Bad Plug in folders are not ignored

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#58]
With e.g. a numberformatexception

Bad paths looking like regular Roddy plugin folder can cause problems:

e.b. ABC_1.0-BACKUP will cause problems

**Comment by dankwart-de** [comment]
Can't reproduce it, code and tests look both fine. I will close this issue if you do not mind.

**Comment by vinjana** [comment]
Like this the issue is solved. But see #108.
