### ISSUE TITLE
Substitute 'dist/bin/current/' by 'dist/bin/develop' and additional changes

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#64]

**Comment by dankwart-de** [comment]
I think we really need to discuss this again. I don't know if it is a wise idea to leave out current. current always stores the latest loader scripts and fixes for these should be available fast. They are independent from the actual processing but are necessary to guarantee a proper startup.

**Comment by vinjana** [comment]
Naveed thinks this **is** a wise idea -- to prevent that production data is analysed with development Roddy versions.

If we can ensure the dist/bin/current/roddy.sh can be run independently from all the other versions and the dir layout outside, I think we don't need a current/ handling of the top-level roddy.sh anymore. Obviously, with a github Roddy we cannot prevent people using development Roddy on production data, but the above solution would break the old bad habbit.

**Comment by dankwart-de** [comment]
Ok, makes sense. How about a switch: --allowcurrent for both Roddy and plugins? Default behaviour would be to disable it.

**Comment by vinjana** [comment]
Hmm, not sure. Let's hear @naveedishaque says. ...

**Comment by dankwart-de** [comment]
As discussed...

- we have moved away from untagged version of software as people are to lazy to pay attention to which version of software that they use

- I see using "current" in Roddy the same as using untagged software

- I truely believe that a normal workflow user should use only tagged versions of roddy, workflows and plugins

- For developers it get's tricky. I would suggest that "current" is replaced with something which is less comfortable like "unstable", "unreleased", "development". This allows the user really differentiation between a released and in development workflow. 



So =>
- current will be renamed to develop
- current needs to be enabled with a command line flag: --enabledevelpment or similar
- development versions of Roddy and the Plugins will not be usable otherwise!
