### ISSUE TITLE
Print an error message, if i/o dir ist not readable or does not exist.

### ISSUE THREAD

**Issue by dankwart-de** [eilslabs/Roddy#68]

**Comment by vinjana** [comment]
This is important on clusters with Kerberos protected data directories. Currently, Roddy silently ignores if the I/O directories are not accessible because of permission problems (may be temporary with Kerberos!) or if they don't exist (e.g. due to misconfiguration).

**Comment by vinjana** [comment]
Duplicate of #114 .
